table customer_master
	lineageTag: 9431fa06-fdbf-4b7a-a40e-a779b756ed71

	column customer_id
		dataType: string
		lineageTag: 1846a6a8-e583-4b50-8d1c-00636573bc42
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_name
		dataType: string
		lineageTag: 6b180cd5-c5af-4db2-b1db-cf6d3bee8f05
		summarizeBy: none
		sourceColumn: customer_name

		annotation SummarizationSetBy = Automatic

	column customer_age
		dataType: int64
		formatString: 0
		lineageTag: 0a69bd4f-1824-4416-8fd4-a7119a4405bc
		summarizeBy: none
		sourceColumn: customer_age

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: cbd83214-5c1a-4da8-a997-a6d4b4b3a8ac
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column customer_segment
		dataType: string
		lineageTag: 9757a15f-0ee0-4f77-be6d-6fdd5e1df270
		summarizeBy: none
		sourceColumn: customer_segment

		annotation SummarizationSetBy = Automatic

	column customer_city
		dataType: string
		lineageTag: 1b6306c1-6f83-4bbe-a305-d5e641f4079f
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

	column customer_state
		dataType: string
		lineageTag: 1fb706b9-3d36-4532-a755-9fc11d69ad82
		summarizeBy: none
		sourceColumn: customer_state

		annotation SummarizationSetBy = Automatic

	column customer_country
		dataType: string
		lineageTag: f1f55d35-f5a4-4339-b906-108dfec901a1
		summarizeBy: none
		sourceColumn: customer_country

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 15b84b44-7068-476b-9fd8-6d58ce5764a4
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column customer_postal_code
		dataType: int64
		formatString: 0
		lineageTag: a126fe5d-b871-4bf0-a592-1d0810a6595b
		summarizeBy: none
		sourceColumn: customer_postal_code

		annotation SummarizationSetBy = Automatic

	column customer_acquisition_cost
		dataType: double
		lineageTag: 03d41d39-27d4-403d-87b0-081a0b3dd095
		summarizeBy: none
		sourceColumn: customer_acquisition_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition customer_master = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\ASDC23\Downloads\customer_master.csv"),[Delimiter=",", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", type text}, {"customer_name", type text}, {"customer_age", Int64.Type}, {"gender", type text}, {"customer_segment", type text}, {"customer_city", type text}, {"customer_state", type text}, {"customer_country", type text}, {"region", type text}, {"customer_postal_code", Int64.Type}, {"customer_acquisition_cost", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

